### ISSUE TITLE
dsd.test() with no Track.path

### ISSUE THREAD

**Issue by jmuth** [faroit/dsdtools#17]
It seems that the provided testing function `dsd.test(my_function)` only provide a mocked rate and array. This can be tricky for function which uses `track.path` to extract song.

A good idea could be either to precise in the README this particularity, or even bether to provide a fully mocked Track object for testing purpose.

**Comment by faroit** [comment]
Hi, thanks for your feedback. That is def an issue. I can fix it soon, but of course, feel free to make a PR

**Comment by faroit** [comment]
Btw. there is a new version coming before [next sisec](http://sisec.inria.fr). It will include some features like: 

* automatic evaluation using bss_eval
* plots and results analysis through pandas
* better support for DNN based methods (keras and pytorch generators)
* provide snippets for every track trough [sisec-mus-trim](https://github.com/faroit/sisec-mus-trim)

**Comment by jmuth** [comment]
Ok, good to know! By _autamatic evalutation_ you mean running the BSS_Eval algorithm in python or just automatically running the matlab BSS_eval ? 

If I have time this next days I write a PR for the issue.

**Comment by faroit** [comment]
> By autamatic evalutation you mean running the BSS_Eval algorithm in python or just automatically running the matlab BSS_eval ?

well we submitted the bss_eval_images to mir_eval last your so we will use this from now on, even though it does not always get bit exact identical to the matlab version. We don't know yet if we will continue to support matlab evaluation in the future, it dependes on the participants, I guess.

**Comment by faroit** [comment]
the new version of dsdtools is renamed to [musdb](https://github.com/sigsep/sigsep-mus-db) It would be nice if you could rework the issue there. Thanks (and hope you submit to sisec 👍 )

**Comment by jmuth** [comment]
OK, I probably won't have time before next year but will try after that. Have a nice day
