### ISSUE TITLE
.mat file import 

### ISSUE THREAD

**Issue by faroit** [faroit/dsdtools#6]
Support already evaluated results from the matlab version of bss_eval

**Comment by faroit** [comment]
added first version in 5e90d71, this can probably be improved and made more rubust

**Comment by faroit** [comment]
A few more issues:

* [ ] not all rows from the matlab evaluation should be imported. Those where `SAR` is `nan` shall be skipped
* a function that imports single .mat files for single tracks is missing
* a function that detects the keys in the mat file so that e.g. only `Dev` results are imported

**Comment by ErikJohnsonCU** [comment]
For the function that detects the keys in the mat file, would that be a separate function where a user would supply the key they wish to import?

**Comment by faroit** [comment]
@ErikJohnsonCU I think we just convert everything thats there... now working in 18ebc6

**Comment by faroit** [comment]
4afe175802ec7786915a5b164bda4bcaf92876e0 addresses

> not all rows from the matlab evaluation should be imported. Those where SAR is nan shall be skipped

@ErikJohnsonCU what do you think?

**Comment by ErikJohnsonCU** [comment]
Isn't your filtering by if any of them have all nans?
